### ISSUE TITLE
Guild Badges not adjusting to size

### ISSUE THREAD

**Issue by whiteboo** [SmolAlli/Themes#12]
I'm not sure if it's just me, but the guild badge is taking up more space than usual with the latest discord update.
![2023-03-01_1355-42123_DiscordPTB_1qmJRtnUKV](https://user-images.githubusercontent.com/10814631/222274162-26eb5fe7-2ebb-4c04-a621-7dfbefac2c17.png)

**Comment by LaShids** [comment]
Same here
![obraz](https://user-images.githubusercontent.com/82770538/222422259-bb7f56f7-f446-4825-87ea-75db8d3b9ddc.png)

**Comment by SmolAlli** [comment]
I have just uploaded the fix for this, please confirm that it now works for you (reload Discord with ctrl r to see the changes)
