### ISSUE TITLE
Server List Hover is Incorrectly Sized

### ISSUE THREAD

**Issue by Thorebourne** [SmolAlli/Themes#15]
the little white dot/bar that shows up when you hover over/click server and Direct Messages is too large and isn't accurate to their actual size.
![Screenshot 2024-07-17 104035](https://github.com/user-attachments/assets/9e4d8e3b-1a71-46b2-8e43-d1fe0ad91e44)

**Comment by SmolAlli** [comment]
Fixed with latest update.
