### ISSUE TITLE
[Suggestion]  -Option to change server list, members, and channel sizes

### ISSUE THREAD

**Issue by BigFlubba** [SmolAlli/Themes#3]
I like how this looks, other than a few weeks. How I have Discord setup is the smallest size possible and I would like to change the sizes of some things that are big and make them smaller and small things and make them bigger. Also, it currently breaks my CSS for folder outlines. Would that be a thing where I have to make a special version for the theme or can it be done on your end?
![image](https://user-images.githubusercontent.com/69104450/152067735-99263532-b0c5-4828-8298-f9f83d2c4ee9.png)

**Comment by BigFlubba** [comment]
Basically in short I would like the option to change the sizes of things and customize some things a bit.

**Comment by SmolAlli** [comment]
I have 3 variables in use currently within the source which is opted to not add into the main file due to them not looking the best when customised. Feel free to add them as such and edit them if you want to, though. Keep in mind that they're more there so that I can use the same value multiple times over, so you may run into some issues.

```
:root {
	/* Variables */
	--guildbar-width: 56px;
	--sidebar-width: 200px;
	--header-height: 40px;
}
```

**Comment by BigFlubba** [comment]
Do you have any variables to change the members and channels size?
![image](https://user-images.githubusercontent.com/69104450/152240618-c8112c6e-bd2f-46ac-98da-8869cf8c41ab.png)
![image](https://user-images.githubusercontent.com/69104450/152240624-1b62181a-51cd-45eb-8362-559335cd6aac.png)
I would like to make the members smaller so they can fit more without scrolling and the same with the channels. Is that feasible with this theme?

**Comment by SmolAlli** [comment]
I will consider it for the future. Right now the only variables I have are the ones I sent before.

**Comment by BigFlubba** [comment]
Got it. Thanks.

**Comment by SmolAlli** [comment]
I will not be adding this.
