### ISSUE TITLE
[Suggestion] - Adding configurable settings for personalization.

### ISSUE THREAD

**Issue by BigFlubba** [SmolAlli/Themes#5]
I do like minimal mode albeit a few caveats. Can the appear on hover for mute and defen buttons have an option to be set to vanilla and sizes for things be baked into the theme file. 

Sry I am a customization nerd, but I just like the looks of vanilla Discord albeit a few things (colors, sizes, and a few other things).

**Comment by SmolAlli** [comment]
Not interested in implementing this.
