### ISSUE TITLE
Settings Button Gone

### ISSUE THREAD

**Issue by whiteboo** [SmolAlli/Themes#8]
Discord updated and now we can't click into user settings on the bottom left.
![image](https://user-images.githubusercontent.com/10814631/183236161-83a3b744-e769-45c3-9dbc-4adacb0009b7.png)

Love the theme by the way. :>

**Comment by Einstein-here** [comment]
Same issue here.

**Comment by net-wayfarer** [comment]
Known, and the fix was already noted by SmolAlli, https://github.com/SmolAlli/Themes/tree/main/MinimalMode#update-important

**Comment by SmolAlli** [comment]
Closed as I already fixed it lol
